In [2]:
import sqlite3
import pandas as pd
import numpy as np

In [3]:
conn = sqlite3.connect("../database/ecommerce.db")

In [4]:
customers= pd.read_sql_query("SELECT * FROM customers",conn)
products = pd.read_sql_query(
    "SELECT * FROM Products",
    conn
)
orders = pd.read_sql_query(
    "SELECT * FROM Orders",
    conn
)
payments = pd.read_sql_query(
    "SELECT * FROM Payments",
    conn
)

In [5]:
pd.read_sql_query("SELECT name FROM sqlite_master WHERE type ='table'",conn)

        name
0  customers
1   Products
2     Orders
3   Payments

In [6]:
customers.head()

   customer_id          name  age  gender       city        state signup_date
0            1  Aarav Sharma   24    Male      Delhi        Delhi  2025-01-10
1            2   Priya Verma   22  Female     Mumbai  Maharashtra  2025-02-15
2            3   Rahul Singh   27    Male  Bangalore    Karnataka  2025-03-01
3            4  Ananya Gupta   23  Female  Hyderabad    Telangana  2025-01-25
4            5  Vikram Patel   29    Male  Ahmedabad      Gujarat  2025-02-12

In [7]:
products.head()

   product_id        product_name     category    price  stock_quantity
0           1           iPhone 15  Electronics  79999.0              50
1           2  Samsung Galaxy S24  Electronics  69999.0              45
2           3     Boat Headphones  Electronics   2499.0             120
3           4  Nike Running Shoes       Sports   4999.0              80
4           5      Adidas T-Shirt      Fashion   1999.0             100

In [8]:
orders.head()

Empty DataFrame
Columns: [order_id, customer_id, product_id, quantity, order_date]
Index: []

In [9]:
payments.head()

Empty DataFrame
Columns: [payment_id, order_id, payment_method, amount, payment_date]
Index: []

In [10]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     0 non-null      object
 1   customer_id  0 non-null      object
 2   product_id   0 non-null      object
 3   quantity     0 non-null      object
 4   order_date   0 non-null      object
dtypes: object(5)
memory usage: 132.0+ bytes

In [11]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  20 non-null     int64
 1   name         20 non-null     object
 2   age          20 non-null     int64
 3   gender       20 non-null     object
 4   city         20 non-null     object
 5   state        20 non-null     object
 6   signup_date  20 non-null     object
dtypes: int64(2), object(5)
memory usage: 1.2+ KB

In [12]:
customers.describe()

       customer_id        age
count     20.00000  20.000000
mean      10.50000  24.650000
std        5.91608   2.300458
min        1.00000  21.000000
25%        5.75000  23.000000
50%       10.50000  24.000000
75%       15.25000  26.250000
max       20.00000  29.000000

In [13]:
orders.shape

(0, 5)

In [14]:
import os
print(os.getcwd())

c:\Users\SYED MOHD HAMZA\OneDrive\Desktop\E-Commerce Sales Analytics\notebook

In [15]:


conn = sqlite3.connect("../database/ecommerce.db")

cursor = conn.cursor()

cursor.execute("SELECT COUNT(*) FROM Orders")
print(cursor.fetchone())

cursor.execute("SELECT COUNT(*) FROM Payments")
print(cursor.fetchone())

(0,)
(0,)

In [16]:
conn.close()

In [17]:
conn =sqlite3.connect("../database/ecommerce.db")
pd.read_sql_query( "SELECT * FROM Orders",conn)
pd.read_sql_query( "SELECT * FROM payments",conn)
pd.read_sql_query( "SELECT * FROM customers",conn)
pd.read_sql_query( "SELECT * FROM products",conn)

,product_id,product_name,category,price,stock_quantity
0,1,iPhone 15,Electronics,79999.0,50
1,2,Samsung Galaxy S24,Electronics,69999.0,45
2,3,Boat Headphones,Electronics,2499.0,120
3,4,Nike Running Shoes,Sports,4999.0,80
4,5,Adidas T-Shirt,Fashion,1999.0,100
5,6,The Psychology of Money,Books,399.0,200
6,7,Atomic Habits,Books,499.0,180
7,8,Mixer Grinder,Home & Kitchen,3499.0,60
8,9,Air Fryer,Home & Kitchen,5999.0,40
9,10,Cricket Bat,Sports,2999.0,70
10,11,Face Wash,Beauty,299.0,250
11,12,Lipstick,Beauty,799.0,150
12,13,Remote Control Car,Toys,1499.0,90
13,14,Building Blocks Set,Toys,999.0,110
14,15,Laptop Backpack,Fashion,1299.0,130

In [18]:
orders.shape

(0, 5)

In [19]:
cursor = conn.cursor()

cursor.execute("SELECT COUNT(*) FROM Orders")
print(cursor.fetchone())

cursor.execute("SELECT COUNT(*) FROM Payments")
print(cursor.fetchone())

(0,)
(0,)

In [20]:
customers.shape

(20, 7)

In [21]:
print(os.listdir("../database"))

['ecommerce.db', 'ecommerce.db-journal', 'ecommerce.sqbpro']

In [22]:
print(os.path.exists("../database/ecommerce.db"))
print(os.path.exists("../database/ecommerce"))

True
False

In [23]:
pd.read_sql_query(
    "SELECT * FROM Orders LIMIT 5",
    conn
)
pd.read_sql_query(
    "SELECT * FROM Payments LIMIT 5",
    conn
)
print(conn)

<sqlite3.Connection object at 0x000001F07918A4D0>

In [24]:
orders.shape

(0, 5)

In [25]:
cursor = conn.cursor()

cursor.execute("SELECT COUNT(*) FROM Orders")
print(cursor.fetchone())

(0,)

In [26]:
import os

print(os.path.abspath("../database/ecommerce.db"))

c:\Users\SYED MOHD HAMZA\OneDrive\Desktop\E-Commerce Sales Analytics\database\ecommerce.db

In [27]:
import os

for root, dirs, files in os.walk(".."):
    for file in files:
        if file.endswith(".db"):
            print(os.path.join(root, file))

..\database\ecommerce.db

In [28]:
cursor.execute("PRAGMA database_list;")
print(cursor.fetchall())

[(0, 'main', 'c:\\Users\\SYED MOHD HAMZA\\OneDrive\\Desktop\\E-Commerce Sales Analytics\\database\\ecommerce.db')]

In [29]:
orders = pd.read_csv("../data/Orders.csv")
payments = pd.read_csv("../data/Payments.csv")

In [30]:
orders.shape

(20, 5)

In [39]:
#total revenue
payments["amount"].sum()
#average order value
payments["amount"].mean()
#total orders
orders.shape[0]
#total customers
customers.shape[0]
#total products
products.shape[0]
#revenue by payment
payments.groupby("payment_method")["amount"].sum()
#top cities by customers
customers["city"].value_counts()
#most expensive products
products.sort_values(by = "price",ascending=False)

,product_id,product_name,category,price,stock_quantity
0,1,iPhone 15,Electronics,79999.0,50
1,2,Samsung Galaxy S24,Electronics,69999.0,45
8,9,Air Fryer,Home & Kitchen,5999.0,40
3,4,Nike Running Shoes,Sports,4999.0,80
7,8,Mixer Grinder,Home & Kitchen,3499.0,60
9,10,Cricket Bat,Sports,2999.0,70
2,3,Boat Headphones,Electronics,2499.0,120
4,5,Adidas T-Shirt,Fashion,1999.0,100
12,13,Remote Control Car,Toys,1499.0,90
14,15,Laptop Backpack,Fashion,1299.0,130
13,14,Building Blocks Set,Toys,999.0,110
11,12,Lipstick,Beauty,799.0,150
6,7,Atomic Habits,Books,499.0,180
5,6,The Psychology of Money,Books,399.0,200
10,11,Face Wash,Beauty,299.0,250